---
title: "L7_Exercise"
output: html_document
date: "2025-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lmerTest)
library(lattice)
library(lme4)
library(MASS)

library(predictmeans)
library(emmeans)
library(multcomp)

```


## R Markdown

```{r}

cucumber<-read.csv("https://www2.compute.dtu.dk/courses/02429/Data/datafiles/cucumber.txt")

cucumber$block<-factor(cucumber$block)
cucumber$section<-factor(cucumber$section)
cucumber$plot<-factor(cucumber$plot)
cucumber$climate<-factor(cucumber$climate)
cucumber$fert<-factor(cucumber$fert)
cucumber$variety<-factor(cucumber$variety)

cucumber

```


block <fctr>, section <fctr>, plot <fctr>, climate <fctr>, fert <fctr>, variety <fctr>, rate <dbl>, level <dbl>

```{r}
m0 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + climate:variety + fert:variety + climate:fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

m1 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + climate:variety + fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

# We drop the three-way interaction with a p-value of 0.4478
anova(m0, m1)

m1 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + climate:variety + fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

m2 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + climate:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

# We keep the interaction between fert and variety with a p-value of 0.01249
anova(m1, m2)

m3 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

# We keep the interaction between climate and variety with a p-value of 0.03983
anova(m1, m3)

m4 <- lmer(rate ~  climate + fert + variety + 
            climate:variety + fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

# We drop the interaction between climate and fert with a p-value of 0.4478
anova(m1, m4)

# thus we get the model:
m5 <- lmer(rate ~  climate + fert + variety + climate:variety + fert:variety + (1|block/section/plot), REML=TRUE, data=cucumber)

```


```{r}
# Only the block parameter seems to be significant!
m5 <- lmer(rate ~  climate + fert + variety + climate:variety + fert:variety + (1|block/section/plot), data=cucumber)
ranova(m5)

m6 <- lmer(rate ~  climate + fert + variety + climate:variety + fert:variety + (1|block/section), data=cucumber)
m7 <- lmer(rate ~  climate + fert + variety + climate:variety + fert:variety + (1|block), data=cucumber)
m8 <- lm(rate ~  climate + fert + variety + climate:variety + fert:variety, data=cucumber)

anova(m5, m6)
anova(m6, m7)
anova(m7, m8)

```

```{r}
anova(m8)
```

```{r}
formula(m8)

formula(m1)
formula(m2)

m7 <- lmer(rate ~  climate + fert + variety + climate:variety + fert:variety + (1|block), data=cucumber)

m9 <- lmer(rate ~  climate + fert + variety  + fert:variety + (1|block), data=cucumber)
m10 <- lmer(rate ~  climate + fert + variety  + climate:variety + (1|block), data=cucumber)

anova(m7, m9)
anova(m7, m10)

```

```{r}
anova(m7)
```


```{r}
m0 <- lmer(rate ~  climate + fert + variety + 
             climate:fert + climate:variety + fert:variety + climate:fert:variety
           + (1|block/section/plot), REML=TRUE, data=cucumber)

anova(m0)
```

