---
title: "WLS"
output: html_document
date: "2026-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Read training data
#! Perhaps you need to set the working directory!?
#setwd("/home/pbac/g/course02417/2025/assignment1")
D <- read.csv("DST_BIL54.csv")
str(D)

# See the help
?strftime
D$time <- as.POSIXct(paste0(D$time,"-01"), "%Y-%m-%d", tz="UTC")
D$time
class(D$time)

## Year to month for each of them
D$year <- 1900 + as.POSIXlt(D$time)$year + as.POSIXlt(D$time)$mon / 12

## Make the output variable a floating point (i.e.\ decimal number)
D$total <- as.numeric(D$total) / 1E6

## Divide intro train and test set
teststart <- as.POSIXct("2024-01-01", tz="UTC")
Dtrain <- D[D$time < teststart, ]
Dtest <- D[D$time >= teststart, ]

### convert time to a variable x
D$x <- 1900 + as.POSIXlt(D$time)$year + as.POSIXlt(D$time)$mon / 12
D$x <- as.numeric(format(D$time, "%Y")) +
          (as.numeric(format(D$time, "%m")) - 1) / 12

# Only keep x and total in d
D <- D[, c("x", "total", "year")]
D$x <- D$x - 2018

Dsmall <- D[, c("x", "total")]

Dtrain <- Dsmall[Dsmall$x < (2024 - 2018), ]
Dtest  <- Dsmall[Dsmall$x >= (2024 - 2018), ]

```



# WLS
```{r}
SIGMA <- diag(n)
rho <- 0.6 
SIGMA[1:5,1:5]
for (row in 1:n) {
  for (col in 1:n) {
    if(row==col) {
      SIGMA[row,col] <- 1
    } else {
      SIGMA[row,col] <- rho^abs(row-col)
    }
  }
}
# print upper corner to check:
SIGMA[1:5,1:5] #looks fine :-)
```

