---
title: "exploration"
output: html_document
---

```{r}
### Read training data
#! Perhaps you need to set the working directory!?
#setwd("/home/pbac/g/course02417/2025/assignment1")
D <- read.csv("DST_BIL54.csv")
str(D)

# See the help
?strftime
D$time <- as.POSIXct(paste0(D$time,"-01"), "%Y-%m-%d", tz="UTC")
D$time
class(D$time)

## Year to month for each of them
D$year <- 1900 + as.POSIXlt(D$time)$year + as.POSIXlt(D$time)$mon / 12

## Make the output variable a floating point (i.e.\ decimal number)
D$total <- as.numeric(D$total) / 1E6

## Divide intro train and test set
teststart <- as.POSIXct("2024-01-01", tz="UTC")
Dtrain <- D[D$time < teststart, ]
Dtest <- D[D$time >= teststart, ]

### convert time to a variable x
D$x <- 1900 + as.POSIXlt(D$time)$year + as.POSIXlt(D$time)$mon / 12
D$x <- as.numeric(format(D$time, "%Y")) +
          (as.numeric(format(D$time, "%m")) - 1) / 12

# Only keep x and total in d
D <- D[, c("x", "total", "year")]
```

```{r}
plot(D$year, D$total,
     type = "l",
     xlab = "Year",
     ylab = "Total (millions)",
     main = "Total Vehicles Over Time")

```


```{r}
# describe the data
summary(D)

# Fit a constant mean model
mean_total <- lm(total ~ 1, data = D)
summary(mean_total)

```

